language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3

env:
  - SYMFONY_VERSION="3.4.*"
  - SYMFONY_VERSION="4.2.*"
  - SYMFONY_VERSION="4.3.*"

matrix:
  exclude:
    # Symfony >= 4.0 PHP requirement is ^7.1.3
    - php: 7.0
      env: SYMFONY_VERSION="4.2.*"
    - php: 7.0
      env: SYMFONY_VERSION="4.3.*"

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - rm -rf composer.lock vendor/
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/workflow:${SYMFONY_VERSION}" --no-update; fi;

install: COMPOSER_MEMORY_LIMIT=-1 travis_retry composer install --prefer-dist --no-interaction

script:
  - vendor/bin/phpunit --coverage-clover=build/coverage/clover.xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/coverage/clover.xml

notifications:
  email: eugone.yann@gmail.com
